### ISSUE TITLE
No module named 'lz4'

### ISSUE THREAD

**Issue by make-all** [jaidenlabelle/tuya-vacuum-maps#2]
The integration seems to depend on lz4, but it is not declared in the manifest, so does not get installed automatically. Probably on many installations it is there already due to other components requiring it, but on mine it was not.

Logger: homeassistant.config_entries
Source: config_entries.py:3249
First occurred: 08:33:15 (2 occurrences)
Last logged: 08:37:28

Error occurred loading flow for integration tuya_vacuum_maps: No module named 'lz4'

**Comment by jaidenlabelle** [comment]
Fixed in v0.1.2

**Comment by make-all** [comment]
Thanks, that was quick. Unfortunately it now gets an identical issue to #1 (I previously didn't recognize that this issue is a variation of that). Seems to be a problem in lz4, there was a PR for it a couple of weeks ago, but it seems to have stalled due to a build failure caused by github infrastructure glitch (https://github.com/python-lz4/python-lz4/pull/294).

**Comment by jaidenlabelle** [comment]
Are you able to check if any version of lz4 is installed using `pip show lz4` while using the ha-venv?

**Comment by jaidenlabelle** [comment]
v0.1.3 removes any specific version requires for lz4 entirely and should fix this problem.

**Comment by make-all** [comment]
Unfortunately this does not fix it. There seems to be a problem with the lz4 package.

```
2024-11-26 11:31:47.813 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package lz4: error: Failed to prepare distributions
  Caused by: Failed to download and build `lz4==4.3.3`
  Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1)
[stdout]
running bdist_wheel
running build
running build_py
creating build/lib.linux-x86_64-cpython-312/lz4
copying lz4/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4
copying lz4/version.py -> build/lib.linux-x86_64-cpython-312/lz4
creating build/lib.linux-x86_64-cpython-312/lz4/block
copying lz4/block/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4/block
creating build/lib.linux-x86_64-cpython-312/lz4/frame
copying lz4/frame/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4/frame
running build_ext
building 'lz4._version' extension
creating build/temp.linux-x86_64-cpython-312/lz4
creating build/temp.linux-x86_64-cpython-312/lz4libs
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -Ilz4libs -I/tmp/.tmpFITZJN/builds-v0/.tmpYfzGmf/include -I/usr/local/include/python3.12 -c lz4/_version.c -o build/temp.linux-x86_64-cpython-312/lz4/_version.o -O3 -Wall -Wundef
[stderr]
/tmp/.tmpFITZJN/builds-v0/.tmpYfzGmf/lib/python3.12/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
/tmp/.tmpFITZJN/builds-v0/.tmpYfzGmf/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:92: UserWarning: version of lz4 already set
  warnings.warn(f"version of {dist_name} already set")
error: command 'gcc' failed: No such file or directory
2024-11-26 11:31:54.149 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package lz4: error: Failed to prepare distributions
  Caused by: Failed to download and build `lz4==4.3.3`
  Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1)
[stdout]
running bdist_wheel
running build
running build_py
creating build/lib.linux-x86_64-cpython-312/lz4
copying lz4/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4
copying lz4/version.py -> build/lib.linux-x86_64-cpython-312/lz4
creating build/lib.linux-x86_64-cpython-312/lz4/block
copying lz4/block/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4/block
creating build/lib.linux-x86_64-cpython-312/lz4/frame
copying lz4/frame/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4/frame
running build_ext
building 'lz4._version' extension
creating build/temp.linux-x86_64-cpython-312/lz4
creating build/temp.linux-x86_64-cpython-312/lz4libs
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -Ilz4libs -I/tmp/.tmpo6GZKj/builds-v0/.tmpMYiJU8/include -I/usr/local/include/python3.12 -c lz4/_version.c -o build/temp.linux-x86_64-cpython-312/lz4/_version.o -O3 -Wall -Wundef
[stderr]
/tmp/.tmpo6GZKj/builds-v0/.tmpMYiJU8/lib/python3.12/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
/tmp/.tmpo6GZKj/builds-v0/.tmpMYiJU8/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:92: UserWarning: version of lz4 already set
  warnings.warn(f"version of {dist_name} already set")
error: command 'gcc' failed: No such file or directory
2024-11-26 11:32:00.011 ERROR (SyncWorker_4) [homeassistant.util.package] Unable to install package lz4: error: Failed to prepare distributions
  Caused by: Failed to download and build `lz4==4.3.3`
  Caused by: Build backend failed to build wheel through `build_wheel` (exit status: 1)
[stdout]
running bdist_wheel
running build
running build_py
creating build/lib.linux-x86_64-cpython-312/lz4
copying lz4/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4
copying lz4/version.py -> build/lib.linux-x86_64-cpython-312/lz4
creating build/lib.linux-x86_64-cpython-312/lz4/block
copying lz4/block/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4/block
creating build/lib.linux-x86_64-cpython-312/lz4/frame
copying lz4/frame/__init__.py -> build/lib.linux-x86_64-cpython-312/lz4/frame
running build_ext
building 'lz4._version' extension
creating build/temp.linux-x86_64-cpython-312/lz4
creating build/temp.linux-x86_64-cpython-312/lz4libs
gcc -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -fno-semantic-interposition -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -DTHREAD_STACK_SIZE=0x100000 -fPIC -Ilz4libs -I/tmp/.tmpBdRcz6/builds-v0/.tmpzGBVeS/include -I/usr/local/include/python3.12 -c lz4/_version.c -o build/temp.linux-x86_64-cpython-312/lz4/_version.o -O3 -Wall -Wundef
[stderr]
/tmp/.tmpBdRcz6/builds-v0/.tmpzGBVeS/lib/python3.12/site-packages/setuptools/_distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_require'
  warnings.warn(msg)
/tmp/.tmpBdRcz6/builds-v0/.tmpzGBVeS/lib/python3.12/site-packages/setuptools_scm/_integration/setuptools.py:92: UserWarning: version of lz4 already set
  warnings.warn(f"version of {dist_name} already set")
error: command 'gcc' failed: No such file or directory
2024-11-26 11:32:00.012 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 567, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 172, in post
    return await self._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 179, in _post_impl
    return await super()._post_impl(request, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 84, in _post_impl
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1301, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1326, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1518, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3268, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3245, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 575, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 54, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 170, in async_get_integration_with_requirements
    await future
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 159, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 182, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 269, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 307, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for tuya_vacuum_maps not found: ['lz4'].
```

**Comment by make-all** [comment]
I confirmed there is no existing install of lz4 in the core container.

**Comment by jaidenlabelle** [comment]
Fixed in v0.1.4 with the removal of lz4 until musllinux build support is added.
